parameters:
#    bw_gallery.example.class: BW\GalleryBundle\Example

services:
#    bw_gallery.example:
#        class: %bw_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
