BW\BlogBundle\Entity\CustomField:
    type: entity
    table: custom_fields
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        expanded:
            type: boolean
        multiple:
            type: boolean
        used:
            type: boolean
    oneToMany:
        customFieldProperties:
            targetEntity: BW\BlogBundle\Entity\CustomFieldProperty
            mappedBy: customField
        productCustomFields:
            targetEntity: BW\ShopBundle\Entity\ProductCustomField
            mappedBy: customField
        postCustomFields:
            targetEntity: BW\BlogBundle\Entity\PostCustomField
            mappedBy: customField
    lifecycleCallbacks: {}
