BW\BlogBundle\Entity\CustomFieldProperty:
    type: entity
    table: custom_field_properties
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        customField:
            targetEntity: BW\BlogBundle\Entity\CustomField
            inversedBy: customFieldProperties
    manyToMany:
        postCustomFields:
            targetEntity: BW\BlogBundle\Entity\PostCustomField
            mappedBy: customFieldProperties
    lifecycleCallbacks: {}
