BW\BlogBundle\Entity\PostCustomField:
    type: entity
    table: post_custom_field
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields: {  }
    manyToOne:
        post:
            targetEntity: BW\BlogBundle\Entity\Post
            inversedBy: postCustomFields
        customField:
            targetEntity: BW\BlogBundle\Entity\CustomField
            inversedBy: postCustomFields
    manyToMany:
        customFieldProperties:
            targetEntity: BW\BlogBundle\Entity\CustomFieldProperty
            inversedBy: postCustomFields
    lifecycleCallbacks: {}
