cart:
    path:     /
    defaults: { _controller: "BWShopBundle:Cart:index" }

cart_clear:
    path:     /clear
    defaults: { _controller: "BWShopBundle:Cart:clear" }

cart_add:
    path:     /add
    defaults: { _controller: "BWShopBundle:Cart:add" }
    methods:  [POST]

cart_remove:
    path:     /remove/{index}
    defaults: { _controller: "BWShopBundle:Cart:remove" }

cart_checkout:
    path:     /checkout
    defaults: { _controller: "BWShopBundle:Cart:checkout" }
    methods:  [POST]
