product_filter_redirect:
    path:     /filter/redirect
    defaults: { _controller: "BWShopBundle:Product:filterRedirect" }
    requirements: {_method: post}

product_list:
    path:     /{filterQuery}
    defaults: { _controller: "BWShopBundle:Product:list", filterQuery: "" }
