product_list:
    path:     /
    defaults: { _controller: "BWShopBundle:Product:list" }

product_filter_form_handle:
    path:     /filter-form-handle
    defaults: { _controller: "BWShopBundle:Product:filterFormHandle" }
    requirements: {_method: post}

product_filter:
    path:     /{filter_query}
    defaults: { _controller: "BWShopBundle:Product:filter" }

