BW\CustomBundle\Entity\Property:
    type: entity
    table: custom_properties
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        field:
            targetEntity: BW\CustomBundle\Entity\Field
            inversedBy: properties
    lifecycleCallbacks: {}
