bw_file:
    resource: "@BWFileBundle/Resources/config/routing.yml"
    prefix:   /

bw_shop:
    resource: "@BWShopBundle/Resources/config/routing.yml"
    prefix:   /

bw_gallery:
    resource: "@BWGalleryBundle/Resources/config/routing.yml"
    prefix:   /

bw_slider:
    resource: "@BWSliderBundle/Resources/config/routing.yml"
    prefix:   /

bw_breadcrumbs:
    resource: "@BWBreadcrumbsBundle/Resources/config/routing.yml"
    prefix:   /

bw_skeleton:
    resource: "@BWSkeletonBundle/Resources/config/routing.yml"
    prefix:   /

bw_mailing:
    resource: "@BWMailingBundle/Resources/config/routing.yml"
    prefix:   /

bw_localization:
    resource: "@BWLocalizationBundle/Resources/config/routing.yml"
    prefix:   /

bw_menu:
    resource: "@BWMenuBundle/Resources/config/routing.yml"
    prefix:   /

bw_user:
    resource: "@BWUserBundle/Resources/config/routing.yml"
    prefix:   /

bw_blog:
    resource: "@BWBlogBundle/Resources/config/routing.yml"
    prefix:   /

# Must be at the end in routes list!
bw_main:
    resource: "@BWMainBundle/Resources/config/routing.yml"
    prefix:   /

# Must be last in routes list!
bw_router:
    resource: "@BWRouterBundle/Resources/config/routing.yml"
    prefix:   /