bw_block:
    resource: "@BWBlockBundle/Resources/config/routing.yml"
    prefix:   /

bw_localization:
    resource: "@BWLocalizationBundle/Resources/config/routing.yml"
    prefix:   /

bw_menu:
    resource: "@BWMenuBundle/Resources/config/routing.yml"
    prefix:   /

bw_user:
    resource: "@BWUserBundle/Resources/config/routing.yml"
    prefix:   /

bw_main:
    resource: "@BWMainBundle/Resources/config/routing.yml"
    prefix:   /

bw_blog:
    resource: "@BWBlogBundle/Resources/config/routing.yml"
    prefix:   /

# Must be last in routes list!
bw_router:
    resource: "@BWRouterBundle/Resources/config/routing.yml"
    prefix:   /