bw_user:
    resource: "@BWUserBundle/Resources/config/routing.yml"
    prefix:   /

bw_main:
    resource: "@BWMainBundle/Resources/config/routing.yml"
    prefix:   /

bw_blog:
    resource: "@BWBlogBundle/Resources/config/routing.yml"
    prefix:   /

