BW\RouterBundle\Entity\Route:
    type: entity
    table: routes
    repositoryClass: BW\RouterBundle\Entity\RouteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        path:
            type: string
            length: 255
            unique: true
        query:
            type: string
            length: 255
        defaults:
            type: array
    manyToOne:
        lang:
            targetEntity: BW\LocalizationBundle\Entity\Lang
    lifecycleCallbacks: {}
