###########
# Backend #
###########
admin_pages:
    host:     %domain%
    pattern:  /_admin/{_locale}/pages
    defaults: { _controller: BWBlogBundle:Admin/Post:posts, _locale: %locale%, type_alias: page }
    
admin_articles:
    host:     %domain%
    pattern:  /_admin/{_locale}/articles
    defaults: { _controller: BWBlogBundle:Admin/Post:posts, _locale: %locale%, type_alias: article }

admin_add_post:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/add
    defaults: { _controller: BWBlogBundle:Admin/Post:post, _locale: %locale% }

admin_edit_post:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/edit/{id}
    defaults: { _controller: BWBlogBundle:Admin/Post:post, _locale: %locale% }
    
admin_toogle_published_post:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/toogle-published/{id}
    defaults: { _controller: BWBlogBundle:Admin/Post:togglePublished, _locale: %locale% }
    
############
# Frontend #
############
posts:
    host:     %domain%
    pattern:  /{_locale}/blog/
    defaults: { _controller: BWBlogBundle:Post:posts, _locale: %locale% }
    
post:
    host:     %domain%
    pattern:  /{_locale}/blog/{slug}
    defaults: { _controller: BWBlogBundle:Post:post, _locale: %locale% }