###########
# Backend #
###########
# Category
admin_categories:
    host:     %domain%
    pattern:  /_admin/{_locale}/categories
    defaults: { _controller: BWBlogBundle:Admin/Category:categories, _locale: %locale% }
    
admin_category_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/category/add
    defaults: { _controller: BWBlogBundle:Admin/Category:category, _locale: %locale% }

admin_category_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/category/edit/{id}
    defaults: { _controller: BWBlogBundle:Admin/Category:category, _locale: %locale% }

admin_category_toogle_published:
    host:     %domain%
    pattern:  /_admin/{_locale}/category/toogle-published/{id}
    defaults: { _controller: BWBlogBundle:Admin/Category:togglePublished, _locale: %locale% }
    
# Post
admin_posts:
    host:     %domain%
    pattern:  /_admin/{_locale}/posts
    defaults: { _controller: BWBlogBundle:Admin/Post:posts, _locale: %locale% }
    
admin_post_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/add
    defaults: { _controller: BWBlogBundle:Admin/Post:post, _locale: %locale% }

admin_post_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/edit/{id}
    defaults: { _controller: BWBlogBundle:Admin/Post:post, _locale: %locale% }

admin_post_toogle_published:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/toogle-published/{id}
    defaults: { _controller: BWBlogBundle:Admin/Post:togglePublished, _locale: %locale% }
    
# Contact
admin_contacts:
    host:     %domain%
    pattern:  /_admin/{_locale}/contacts
    defaults: { _controller: BWBlogBundle:Admin/Contact:contacts, _locale: %locale% }
  
admin_contact_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/contact/add
    defaults: { _controller: BWBlogBundle:Admin/Contact:contact, _locale: %locale% }

admin_contact_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/contact/edit/{id}
    defaults: { _controller: BWBlogBundle:Admin/Contact:contact, _locale: %locale% }
    
# Contact
admin_custom_fields:
    host:     %domain%
    pattern:  /_admin/{_locale}/custom-fields
    defaults: { _controller: BWBlogBundle:Admin/CustomField:customFields, _locale: %locale% }
  
admin_custom_field_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/custom-field/add
    defaults: { _controller: BWBlogBundle:Admin/CustomField:customField, _locale: %locale% }

admin_custom_field_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/custom-field/edit/{id}
    defaults: { _controller: BWBlogBundle:Admin/CustomField:customField, _locale: %locale% }
    
############
# Frontend #
############
    
# Posts
#post:
#    host:     %domain%
#    pattern:  /{_locale}/post/{slug}
#    defaults: { _controller: BWBlogBundle:Post:post, _locale: %locale% }