###########
# Backend #
###########
# Pages
admin_pages:
    host:     %domain%
    pattern:  /_admin/{_locale}/pages
    defaults: { _controller: BWBlogBundle:Admin/Page:pages, _locale: %locale% }
    
admin_page_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/page/add
    defaults: { _controller: BWBlogBundle:Admin/Page:page, _locale: %locale% }

admin_page_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/page/edit/{id}
    defaults: { _controller: BWBlogBundle:Admin/Page:page, _locale: %locale% }

admin_page_toogle_published:
    host:     %domain%
    pattern:  /_admin/{_locale}/page/toogle-published/{id}
    defaults: { _controller: BWBlogBundle:Admin/Page:togglePublished, _locale: %locale% }

# Articles
admin_articles:
    host:     %domain%
    pattern:  /_admin/{_locale}/articles
    defaults: { _controller: BWBlogBundle:Admin/Article:articles, _locale: %locale% }
    
admin_article_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/article/add
    defaults: { _controller: BWBlogBundle:Admin/Article:article, _locale: %locale% }

admin_article_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/article/edit/{id}
    defaults: { _controller: BWBlogBundle:Admin/Article:article, _locale: %locale% }
    
admin_article_toogle_published:
    host:     %domain%
    pattern:  /_admin/{_locale}/article/toogle-published/{id}
    defaults: { _controller: BWBlogBundle:Admin/Article:togglePublished, _locale: %locale% }
    
############
# Frontend #
############
# Pages
page:
    host:     %domain%
    pattern:  /{_locale}/page/{slug}
    defaults: { _controller: BWBlogBundle:Page:page, _locale: %locale% }

# Articles
articles:
    host:     %domain%
    pattern:  /{_locale}/blog/
    defaults: { _controller: BWBlogBundle:Article:articles, _locale: %locale% }
    
article:
    host:     %domain%
    pattern:  /{_locale}/blog/{slug}
    defaults: { _controller: BWBlogBundle:Article:article, _locale: %locale% }