###########
# Backend #
###########
# Category
admin_categories:
    host:     %domain%
    pattern:  /_admin/{_locale}/categories
    defaults: { _controller: BWBlogBundle:Admin/Category:categories, _locale: %locale% }
    
admin_category_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/category/add
    defaults: { _controller: BWBlogBundle:Admin/Category:category, _locale: %locale% }

admin_category_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/category/{id}/edit
    defaults: { _controller: BWBlogBundle:Admin/Category:category, _locale: %locale% }

admin_category_toogle_published:
    host:     %domain%
    pattern:  /_admin/{_locale}/category/{id}/toogle-published
    defaults: { _controller: BWBlogBundle:Admin/Category:togglePublished, _locale: %locale% }
    
# Post
admin_posts:
    host:     %domain%
    pattern:  /_admin/{_locale}/posts
    defaults: { _controller: BWBlogBundle:Admin/Post:posts, _locale: %locale% }
    
admin_post_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/add
    defaults: { _controller: BWBlogBundle:Admin/Post:post, _locale: %locale% }

admin_post_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/{id}/edit
    defaults: { _controller: BWBlogBundle:Admin/Post:post, _locale: %locale% }

admin_post_toogle_published:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/{id}/toogle-published
    defaults: { _controller: BWBlogBundle:Admin/Post:togglePublished, _locale: %locale% }
    
# Contact
admin_contacts:
    host:     %domain%
    pattern:  /_admin/{_locale}/contacts
    defaults: { _controller: BWBlogBundle:Admin/Contact:contacts, _locale: %locale% }
  
admin_contact_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/contact/add
    defaults: { _controller: BWBlogBundle:Admin/Contact:contact, _locale: %locale% }

admin_contact_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/contact/{id}/edit
    defaults: { _controller: BWBlogBundle:Admin/Contact:contact, _locale: %locale% }
    
# Custom Fields 
admin_custom_fields:
    host:     %domain%
    pattern:  /_admin/{_locale}/custom-fields
    defaults: { _controller: BWBlogBundle:Admin/CustomField:customFields, _locale: %locale% }
  
admin_custom_field_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/custom-field/add
    defaults: { _controller: BWBlogBundle:Admin/CustomField:customField, _locale: %locale% }

admin_custom_field_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/custom-field/{id}/edit
    defaults: { _controller: BWBlogBundle:Admin/CustomField:customField, _locale: %locale% }
  
# Custom Field Properties
admin_custom_field_property_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/custom-field/{field_id}/property/add
    defaults: { _controller: BWBlogBundle:Admin/CustomFieldProperty:customFieldProperty, _locale: %locale% }

admin_custom_field_property_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/custom-field/{field_id}/property/{id}/edit
    defaults: { _controller: BWBlogBundle:Admin/CustomFieldProperty:customFieldProperty, _locale: %locale% }
    
############
# Frontend #
############
search:
    host:     %domain%
    pattern:  /{_locale}/search
    defaults: { _controller: BWBlogBundle:Search:index, _locale: %locale% }
# Posts
#post:
#    host:     %domain%
#    pattern:  /{_locale}/post/{slug}
#    defaults: { _controller: BWBlogBundle:Post:post, _locale: %locale% }