###########
# Backend #
###########
# Posts
admin_posts:
    host:     %domain%
    pattern:  /_admin/{_locale}/posts
    defaults: { _controller: BWBlogBundle:Admin/Post:posts, _locale: %locale% }
    
admin_post_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/add
    defaults: { _controller: BWBlogBundle:Admin/Post:post, _locale: %locale% }

admin_post_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/edit/{id}
    defaults: { _controller: BWBlogBundle:Admin/Post:post, _locale: %locale% }

admin_post_toogle_published:
    host:     %domain%
    pattern:  /_admin/{_locale}/post/toogle-published/{id}
    defaults: { _controller: BWBlogBundle:Admin/Post:togglePublished, _locale: %locale% }
    
############
# Frontend #
############
# Posts
post:
    host:     %domain%
    pattern:  /{_locale}/post/{slug}
    defaults: { _controller: BWBlogBundle:Post:post, _locale: %locale% }