###########
# BACKEND #
###########
admin_root:
    host:     %domain%
    pattern:  /_admin/
    defaults:
        _controller:  FrameworkBundle:Redirect:urlRedirect
        path:         /_admin/%locale%/
        permanent:    true

admin:
    host:     %domain%
    pattern:  /_admin/{_locale}/
    defaults: { _controller: BWMainBundle:Admin/Main:index, _locale: %locale% }

admin_config:
    host:     %domain%
    pattern:  /_admin/{_locale}/config
    defaults: { _controller: BWMainBundle:Admin/Main:config, _locale: %locale% }
    

############
# FRONTEND #
############
home_root:
    host:     %domain%
    pattern:  /
    defaults:
        _controller:  FrameworkBundle:Redirect:urlRedirect
        path:         /%locale%/
        permanent:    true

home:
    host:     %domain%
    pattern:  /{_locale}/
    defaults: { _controller: BWMainBundle:Main:index }
        
demo:
    host:     %domain%
    pattern:  /{_locale}/demo
    defaults: { _controller: BWMainBundle:Demo:index }
#    requirements:
#        _locale: en|ru|ua|de