###########
# BACKEND #
###########
admin:
    host:     %domain%
    pattern:  /_admin/{_locale}/
    defaults: { _controller: BWMainBundle:Admin/Main:index, _locale: %locale% }

admin_config:
    host:     %domain%
    pattern:  /_admin/{_locale}/config
    defaults: { _controller: BWMainBundle:Admin/Main:config, _locale: %locale% }
    

############
# FRONTEND #
############
home:
    host:     %domain%
    pattern:  /{_locale}/
    defaults: { _controller: BWMainBundle:Main:index }
    