parameters:
#    bw_localization.example.class: BW\LocalizationBundle\Example

services:
#    bw_localization.example:
#        class: %bw_localization.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    bw.localization.lang:
        class: BW\LocalizationBundle\Service\LangService
        arguments: ["@service_container"]