parameters:
#    bw_custom.example.class: BW\CustomBundle\Example

services:
#    bw_custom.example:
#        class: %bw_custom.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
