admin_slider_groups:
    host:     %domain%
    pattern:  /_admin/{_locale}/slider-groups
    defaults: { _controller: BWSliderBundle:Admin/Group:groups, _locale: %locale% }

admin_slider_group_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/slider-group/add
    defaults: { _controller: BWSliderBundle:Admin/Group:group, _locale: %locale% }

admin_slider_group_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/slider-group/{id}/edit
    defaults: { _controller: BWSliderBundle:Admin/Group:group, _locale: %locale% }

admin_slider_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/slider/add
    defaults: { _controller: BWSliderBundle:Admin/Slider:slider, _locale: %locale% }
    
admin_slider_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/slider/{id}/edit
    defaults: { _controller: BWSliderBundle:Admin/Slider:slider, _locale: %locale% }
    
admin_slide_add:
    host:     %domain%
    pattern:  /_admin/{_locale}/slide/add
    defaults: { _controller: BWSliderBundle:Admin/Slide:slide, _locale: %locale% }
    
admin_slide_edit:
    host:     %domain%
    pattern:  /_admin/{_locale}/slide/{id}/edit
    defaults: { _controller: BWSliderBundle:Admin/Slide:slide, _locale: %locale% }