BW\GalleryBundle\Entity\Photo:
    type: entity
    table: photos
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        shortDescription:
            type: text
    oneToOne:
        smallImage:
            targetEntity: BW\BlogBundle\Entity\Image
            joinColumn:
                name: small_image_id
                referencedColumnName: id
            cascade: [persist, remove]
        bigImage:
            targetEntity: BW\BlogBundle\Entity\Image
            joinColumn:
                name: big_image_id
                referencedColumnName: id
            cascade: [persist, remove]
    manyToOne:
        gallery:
            targetEntity: BW\GalleryBundle\Entity\Gallery
            inversedBy: photos
    lifecycleCallbacks: {}
