parameters:
#    bw_menu.example.class: BW\MenuBundle\Example

services:
#    bw_menu.example:
#        class: %bw_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw.twig.bw_extension:
        class: BW\MainBundle\Twig\BWExtension
        tags:
            - { name: twig.extension }