parameters:
#    bw_block.example.class: BW\BlockBundle\Example

services:
#    bw_block.example:
#        class: %bw_block.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    bw.block:
        class: BW\BlockBundle\Service\BlockService
        arguments: ["@service_container"]