############
# Frontend #
############
# Users
user_sign_up:
    pattern:  /user/sign-up
    defaults: { _controller: BWUserBundle:User:signUp }
    
user_sign_in:
    pattern:  /user/sign-in
    defaults:  { _controller: BWUserBundle:User:signIn }
    
user_sign_in_check:
    pattern:  /user/sign-in-check
    
user_sign_out:
    pattern:  /user/sign-out
    
user_password_reset:
    pattern:  /user/password-reset
    defaults: { _controller: BWUserBundle:User:passwordReset }

###########
# Backend #
###########
# Users
admin_users:
    pattern:  /_admin/users
    defaults: { _controller: BWUserBundle:Admin/User:users }
    
admin_user_add:
    pattern:  /_admin/user/add
    defaults: { _controller: BWUserBundle:Admin/User:user }

admin_user_edit:
    pattern:  /_admin/user/edit/{id}
    defaults: { _controller: BWUserBundle:Admin/User:user }
    
admin_user_toogle_active:
    pattern:  /_admin/user/toogle-active/{id}
    defaults: { _controller: BWUserBundle:Admin/User:toogleActive }
    
# Roles
admin_roles:
    pattern:  /_admin/roles
    defaults: { _controller: BWUserBundle:Admin/Role:roles }
    
admin_role_add:
    pattern:  /_admin/role/add
    defaults: { _controller: BWUserBundle:Admin/Role:role }
    
admin_role_edit:
    pattern:  /_admin/role/edit/{id}
    defaults: { _controller: BWUserBundle:Admin/Role:role }