parameters:
#    bw_user.example.class: BW\UserBundle\Example

    social:
        vkontakte:
            is_active: true
            app_id: 4119845
            secret: 2eJ770PwIIBibuAoC5Pb
            scopes: [notify]
            response_type: code
      
        facebook:
            is_active: true
            app_id: 440949559366247
            secret: cc8777ecc06d46368863bb5947071d98
            scopes: [email]
            #redirect_uri: http://bow.loc/web/%locale%/user/sign-in

        google:
            is_active: true
            client_id: 217012306960-vi6djap9rmnfg4lf6079nsfee64vag4m.apps.googleusercontent.com
            client_secret: A7GUTAFWb9iUML6KsWn8Td-W
            redirect_uri: http://ndv.net.ua/redirect.php
            developer_key: AIzaSyAuFpsZo7mTzmAv36mUgROHcSPw-N-ZjiI
            scopes: [https://www.googleapis.com/auth/plus.me, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile]

services:
#    bw_user.example:
#        class: %bw_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    
    bw.user.social:
        class: BW\UserBundle\Service\SocialService
        arguments: [%social%]
        
    bw.user.service:
        class: BW\UserBundle\Service\UserService
        arguments: ["@service_container"]
        
    bw_user.password_encoder.listener:
        class: BW\UserBundle\EventListener\PasswordEncoder
        arguments: ["@security.encoder_factory"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }