parameters:
#    bw_user.example.class: BW\UserBundle\Example

services:
#    bw_user.example:
#        class: %bw_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    bw.user.service:
        class: BW\UserBundle\Service\UserService
        arguments: ["@service_container"]
        
    bw_user.password_encoder.listener:
        class: BW\UserBundle\EventListener\PasswordEncoder
        arguments: ["@security.encoder_factory"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }