parameters:
#    bw_user.example.class: BW\UserBundle\Example

    social.facebook:
        is_active: true
        app_id: 440949559366247
        secret: cc8777ecc06d46368863bb5947071d98
        #For Login URL:
        params:
            scope: [email]
            #redirect_uri: http://bow.loc/web/%locale%/user/sign-in

services:
#    bw_user.example:
#        class: %bw_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    
    bw.user.social:
        class: BW\UserBundle\Service\SocialService
        arguments: [%social.facebook%]
        
    bw.user.service:
        class: BW\UserBundle\Service\UserService
        arguments: ["@service_container"]
        
    bw_user.password_encoder.listener:
        class: BW\UserBundle\EventListener\PasswordEncoder
        arguments: ["@security.encoder_factory"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }