BW\ShopBundle\Entity\Delivery:
    type: entity
    table: shop_delivery
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
    oneToMany:
        orders:
            targetEntity: BW\ShopBundle\Entity\Delivery
            mappedBy: delivery
    lifecycleCallbacks: {  }
