BW\ShopBundle\Entity\OrderedProduct:
    type: entity
    table: shop_ordered_product
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
        price:
            type: decimal
            precision: 12
            scale: 2
    manyToOne:
        product:
            targetEntity: BW\ShopBundle\Entity\Product
        order:
            targetEntity: BW\ShopBundle\Entity\Order
            inversedBy: orderedProducts
    lifecycleCallbacks: {  }
