BW\ShopBundle\Entity\Order:
    type: entity
    table: shop_order
    entityListeners:
        BW\ShopBundle\EventListener\OrderListener:
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    oneToMany:
        orderedProducts:
            targetEntity: BW\ShopBundle\Entity\OrderedProduct
            mappedBy: order
            cascade: [persist]
    manyToOne:
        status:
            targetEntity: BW\ShopBundle\Entity\Status
            inversedBy: orders
        delivery:
            targetEntity: BW\ShopBundle\Entity\Delivery
            inversedBy: orders
        payment:
            targetEntity: BW\ShopBundle\Entity\Payment
            inversedBy: orders
    lifecycleCallbacks: {  }
