BW\ShopBundle\Entity\Product:
    type: entity
    table: shop_products
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        published:
            type: boolean
        recent:
            type: boolean
        featured:
            type: boolean
        popular:
            type: boolean
        sku:
            type: string
            length: 255
        price:
            type: decimal
            scale: 2
            precision: 12
        heading:
            type: string
            length: 255
        shortDescription:
            type: text
        description:
            type: text
        slug:
            type: string
            length: 255
        title:
            type: string
            length: 255
        metaDescription:
            type: string
            length: 255
        created:
            type: datetime
        updated:
            type: datetime
    oneToMany:
        productImages:
            targetEntity: BW\ShopBundle\Entity\ProductImage
            mappedBy: product
            cascade: [persist, remove]
        productFields:
            targetEntity: BW\ShopBundle\Entity\ProductField
            mappedBy: product
            cascade: [persist, remove]
    manyToOne:
        category:
            targetEntity: BW\ShopBundle\Entity\Category
            inversedBy: products
        vendor:
            targetEntity: BW\ShopBundle\Entity\Vendor
            inversedBy: products
        route:
            targetEntity: BW\RouterBundle\Entity\Route
            cascade: [persist, remove]
    lifecycleCallbacks: {  }
