BW\ShopBundle\Entity\ProductField:
    type: entity
    table: shop_product_custom_fields
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields: {}
    manyToOne:
        product:
            targetEntity: BW\ShopBundle\Entity\Product
            inversedBy: productFields
        field:
            targetEntity: BW\CustomBundle\Entity\Field
    manyToMany:
        properties:
            targetEntity: BW\CustomBundle\Entity\Property
    lifecycleCallbacks: {}
