BW\ShopBundle\Entity\Product:
    type: entity
    table: products
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        published:
            type: boolean
        recent:
            type: boolean
        featured:
            type: boolean
        popular:
            type: boolean
        sku:
            type: string
            length: 255
        price:
            type: decimal
            scale: 2
            precision: 12
        heading:
            type: string
            length: 255
        shortDescription:
            type: text
        description:
            type: text
        slug:
            type: string
            length: 255
        title:
            type: string
            length: 255
        metaDescription:
            type: string
            length: 255
    manyToOne:
        vendor:
            targetEntity: BW\ShopBundle\Entity\Vendor
            inversedBy: products
    lifecycleCallbacks: {  }
