bw_shop_vendor_admin:
    resource: "@BWShopBundle/Resources/config/routing/vendor_admin.yml"
    prefix:   /_admin/{_locale}/vendor

bw_shop_vendor:
    resource: "@BWShopBundle/Resources/config/routing/vendor.yml"
    prefix:   /{_locale}/vendors

bw_shop_product_admin:
    resource: "@BWShopBundle/Resources/config/routing/product_admin.yml"
    prefix:   /_admin/{_locale}/product
