bw_shop_vendor_admin:
    resource: "@BWShopBundle/Resources/config/routing/vendor_admin.yml"
    prefix:   /_admin/{_locale}/shop/vendor

bw_shop_vendor:
    resource: "@BWShopBundle/Resources/config/routing/vendor.yml"
    prefix:   /{_locale}/vendors

bw_shop_category_admin:
    resource: "@BWShopBundle/Resources/config/routing/category_admin.yml"
    prefix:   /_admin/{_locale}/shop/category

bw_shop_category:
    resource: "@BWShopBundle/Resources/config/routing/category.yml"
    prefix:   /{_locale}/categories

bw_shop_product_admin:
    resource: "@BWShopBundle/Resources/config/routing/product_admin.yml"
    prefix:   /_admin/{_locale}/shop/product

bw_shop_product:
    resource: "@BWShopBundle/Resources/config/routing/product.yml"
    prefix:   /{_locale}/products
