parameters:
#    bw_shop.example.class: BW\ShopBundle\Example

services:
#    bw_shop.example:
#        class: %bw_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_shop.service.product_filter:
        class: 'BW\ShopBundle\Service\ProductFilterService'
        arguments: ['@service_container']

    bw_shop.service.discount_product_widget:
        class: 'BW\ShopBundle\Service\DiscountProductWidgetService'
        arguments: ['@doctrine.orm.entity_manager', '@templating']

    bw_shop.service.best_seller_product_widget:
        class: 'BW\ShopBundle\Service\BestSellerProductWidgetService'
        arguments: ['@doctrine.orm.entity_manager', '@templating']

    bw_shop.service.recent_product_widget:
        class: 'BW\ShopBundle\Service\RecentProductWidgetService'
        arguments: ['@doctrine.orm.entity_manager', '@templating']

    bw_shop.service.featured_product_widget:
        class: 'BW\ShopBundle\Service\FeaturedProductWidgetService'
        arguments: ['@doctrine.orm.entity_manager', '@templating']

    bw_shop.service.cart:
        class: 'BW\ShopBundle\Service\CartService'
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '@router', '@request_stack']

    bw_shop.twig.cart:
        public: false
        class: BW\ShopBundle\Twig\CartExtension
        arguments: ['@bw_shop.service.cart']
        tags:
            - { name: twig.extension }

    bw_shop.event_listener.order:
        public: false
        class: \BW\ShopBundle\EventListener\OrderListener
        arguments: []
