parameters:
#    bw_shop.example.class: BW\ShopBundle\Example
    bw_shop.service.product_filter.class: BW\ShopBundle\Service\ProductFilterService

services:
#    bw_shop.example:
#        class: %bw_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    bw_shop.service.product_filter:
        class: %bw_shop.service.product_filter.class%
        arguments: ["@service_container"]
